dist: bionic
language: python
python: "3.7"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install libgit2-dev libudunits2-dev
  - sudo apt-get install python3-setuptools python3-pip
  - rvm default
  - gem install json kramdown jekyll bundler

install:
  - sudo -H pip3 install -U pyyaml
script:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install
  - make lesson-check-all
  - make --always-make site


# Header
sudo: false
cache: packages
latex: false

branches:
  only:
  - gh-pages
  - /.*/

# Add spellchecking for PRs
jobs:
  include:
    - stage: spelling
      language: python
      sudo: true
      python: "3.7"
      # The default before_install step is slow
      before_install:
      # Use codespell for spell checking
      install:
        sudo pip install codespell
      script: codespell --skip="assets,fig,*.svg,AUTHORS,.mailmap,Dockerfile" --quiet-level=2 --ignore-words-list="rouge,keyserver"
    - stage: check_and_build
